name: mr_recon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - frankong
dependencies:
  - cupy
  - einops
  - ipykernel
  - libgomp
  - libxcrypt
  - matplotlib
  - nccl
  - numpy==1.22.4
  - pydicom
  - python=3.10
  - pytorch-cuda=11.8
  - scikit-image
  - sigpy
  - torchaudio
  - torchvision
  - pip:
      - cvxpy
      - fast-pytorch-kmeans
      - fire
      - flt
      - gdown
      - igrog
      - ipympl
      - ismrmrd
      - mat73
      - nibabel
      - torchkbnufft
      - triton
      - twixtools