name: mr_recon
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cupy
  - einops
  - ipykernel
  - libgomp
  - libxcrypt
  - matplotlib
  - nccl
  - numpy==1.22.4
  - pip=24.0
  - python=3.10
  - pytorch-cuda=11.8
  - scikit-image
  - torchaudio
  - torchvision
  - pip:
      - cvxpy
      - fast-pytorch-kmeans
      - sigpy
      - torchkbnufft